INSERT INTO `db`.`address`(`id`, `title`, `address_line1`, `address_line2`,`town`, `state_or_province`, `post_code`, `country_id`, `latitude`, `longtitude`, `contact_telephone1`,`contact_telephone2`, `contact_email`, `access_comments`, `relatedurl`, `general_comments`)
    VALUES(2389, "Southern California Edison - Rosemead Office Building 1", "2244 Walnut Grove Ave", null, "Rosemead", "CA", "91770", 2, 34.050745, -118.081014, "", null, null, "Employee use only", "http://greenlots.com/", null);
INSERT INTO `db`.`address`(`id`, `title`, `address_line1`, `address_line2`,`town`, `state_or_province`, `post_code`, `country_id`, `latitude`, `longtitude`, `contact_telephone1`,`contact_telephone2`, `contact_email`, `access_comments`, `relatedurl`, `general_comments`)
    VALUES(2390, "Los Angeles Convention Center", "1201 S Figueroa St", null, "Los Angeles", "CA", "90015", 2, 34.04057, -118.268762, "213-741-1151", null, null, "24 hours daily; pay lot", "", null);
INSERT INTO `db`.`address`(`id`, `title`, `address_line1`, `address_line2`,`town`, `state_or_province`, `post_code`, `country_id`, `latitude`, `longtitude`, `contact_telephone1`,`contact_telephone2`, `contact_email`, `access_comments`, `relatedurl`, `general_comments`)
    VALUES(2392, "LADWP - John Ferraro Building", "111 N Hope St", null, "Los Angeles", "CA", "90012", 2, 34.058476, -118.24819, "", null, null, "For fleet and employee use only", "", null);
INSERT INTO `db`.`address`(`id`, `title`, `address_line1`, `address_line2`,`town`, `state_or_province`, `post_code`, `country_id`, `latitude`, `longtitude`, `contact_telephone1`,`contact_telephone2`, `contact_email`, `access_comments`, `relatedurl`, `general_comments`)
    VALUES(2397, "State Capitol Parking Garage", "1303 10th St", null, "Sacramento", "CA", "95814", 2, 38.576769, -121.495022, "", null, null, "Permitted state legislators only", "", null);
INSERT INTO `db`.`address`(`id`, `title`, `address_line1`, `address_line2`,`town`, `state_or_province`, `post_code`, `country_id`, `latitude`, `longtitude`, `contact_telephone1`,`contact_telephone2`, `contact_email`, `access_comments`, `relatedurl`, `general_comments`)
    VALUES(2399, "Hewlett Packard", "19111 Pruneridge Ave", "", "Cupertino", "CA", "95014", 2, 37.332446, -122.008913, "", "", "", "Building 42 & 46. ", "", null);
INSERT INTO `db`.`address`(`id`, `title`, `address_line1`, `address_line2`,`town`, `state_or_province`, `post_code`, `country_id`, `latitude`, `longtitude`, `contact_telephone1`,`contact_telephone2`, `contact_email`, `access_comments`, `relatedurl`, `general_comments`)
    VALUES(2400, "CITYOFSANTAROSA", "100 Santa Rosa Ave", null, "Santa Rosa", "CA", "95404", 2, 38.4380517, -122.711357, "888-758-4389", null, null, "24 hours daily", "http://www.mychargepoint.net/", null);
INSERT INTO `db`.`address`(`id`, `title`, `address_line1`, `address_line2`,`town`, `state_or_province`, `post_code`, `country_id`, `latitude`, `longtitude`, `contact_telephone1`,`contact_telephone2`, `contact_email`, `access_comments`, `relatedurl`, `general_comments`)
    VALUES(2408, "LADWP - Ducommun Center", "433 E Temple St", null, "Los Angeles", "CA", "90012", 2, 34.051852, -118.236702, "", null, null, "", "", null);
INSERT INTO `db`.`address`(`id`, `title`, `address_line1`, `address_line2`,`town`, `state_or_province`, `post_code`, `country_id`, `latitude`, `longtitude`, `contact_telephone1`,`contact_telephone2`, `contact_email`, `access_comments`, `relatedurl`, `general_comments`)
    VALUES(2409, "California Air Resources Board", "9530 Telstar Ave", null, "El Monte", "CA", "91731", 2, 34.06872, -118.064, "626-575-6800", null, null, "24 hours daily", "", null);
INSERT INTO `db`.`address`(`id`, `title`, `address_line1`, `address_line2`,`town`, `state_or_province`, `post_code`, `country_id`, `latitude`, `longtitude`, `contact_telephone1`,`contact_telephone2`, `contact_email`, `access_comments`, `relatedurl`, `general_comments`)
    VALUES(2413, "HPE SAN JOSE", "3000 Hanover St", null, "Palo Alto", "CA", "94304", 2, 37.416434, -122.145904, "888-758-4389", null, null, "24 hours daily", "http://www.chargepoint.com/", null);
INSERT INTO `db`.`address`(`id`, `title`, `address_line1`, `address_line2`,`town`, `state_or_province`, `post_code`, `country_id`, `latitude`, `longtitude`, `contact_telephone1`,`contact_telephone2`, `contact_email`, `access_comments`, `relatedurl`, `general_comments`)
    VALUES(2442, "City of Pasadena - De Lacey Garage", "45 De Lacey Ave", null, "Pasadena", "CA", "91105", 2, 34.145015, -118.152223, "626-744-7665", null, null, "24 hours daily; pay lot", "", null);
INSERT INTO `db`.`address`(`id`, `title`, `address_line1`, `address_line2`,`town`, `state_or_province`, `post_code`, `country_id`, `latitude`, `longtitude`, `contact_telephone1`,`contact_telephone2`, `contact_email`, `access_comments`, `relatedurl`, `general_comments`)
    VALUES(2443, "City of Pasadena - Schoolhouse Garage", "33 E Green St", null, "Pasadena", "CA", "91105", 2, 34.144506, -118.150015, "626-744-7665", null, null, "24 hours daily; pay lot", "", null);
INSERT INTO `db`.`address`(`id`, `title`, `address_line1`, `address_line2`,`town`, `state_or_province`, `post_code`, `country_id`, `latitude`, `longtitude`, `contact_telephone1`,`contact_telephone2`, `contact_email`, `access_comments`, `relatedurl`, `general_comments`)
    VALUES(2444, "Pasadena Hilton", "150 S Los Robles", null, "Pasadena", "CA", "91101", 2, 34.142973, -118.140553, "626-577-1000", null, null, "24 hours daily; for guest use only", "", null);
INSERT INTO `db`.`address`(`id`, `title`, `address_line1`, `address_line2`,`town`, `state_or_province`, `post_code`, `country_id`, `latitude`, `longtitude`, `contact_telephone1`,`contact_telephone2`, `contact_email`, `access_comments`, `relatedurl`, `general_comments`)
    VALUES(2476, "Ontario Airport Hilton", "700 N Haven Ave", null, "Ontario", "CA", "91764", 2, 34.07122, -117.575, "909-980-0400", null, null, "24 hours daily; guest use only", "", null);
INSERT INTO `db`.`address`(`id`, `title`, `address_line1`, `address_line2`,`town`, `state_or_province`, `post_code`, `country_id`, `latitude`, `longtitude`, `contact_telephone1`,`contact_telephone2`, `contact_email`, `access_comments`, `relatedurl`, `general_comments`)
    VALUES(2477, "Courtyard Marriott - Oxnard Ventura", "600 E Esplanade Dr", null, "Oxnard", "CA", "93030", 2, 34.22787288200444, -119.172278485775, "1-805-988-3600", null, null, "Charging station is located at the southeast side of the hotel", "http://www.marriott.com/hotels/travel/oxrvo-courtyard-oxnard-ventura/", null);
INSERT INTO `db`.`address`(`id`, `title`, `address_line1`, `address_line2`,`town`, `state_or_province`, `post_code`, `country_id`, `latitude`, `longtitude`, `contact_telephone1`,`contact_telephone2`, `contact_email`, `access_comments`, `relatedurl`, `general_comments`)
    VALUES(2482, "CNTYOFRIVERSIDE", "3535 12th Street", null, "Riverside", "CA", "92501", 2, 33.977163, -117.374653, "888-758-4389", null, null, "24 hours daily", "http://www.chargepoint.com/", null);
INSERT INTO `db`.`address`(`id`, `title`, `address_line1`, `address_line2`,`town`, `state_or_province`, `post_code`, `country_id`, `latitude`, `longtitude`, `contact_telephone1`,`contact_telephone2`, `contact_email`, `access_comments`, `relatedurl`, `general_comments`)
    VALUES(2483, "Inland Empire Foods", "5425 Wilson St", null, "Riverside", "CA", "92509", 2, 34.0189, -117.38, "951-682-8222", null, null, "24 hours M-Th, 12am-4:30pm F", "", null);
INSERT INTO `db`.`address`(`id`, `title`, `address_line1`, `address_line2`,`town`, `state_or_province`, `post_code`, `country_id`, `latitude`, `longtitude`, `contact_telephone1`,`contact_telephone2`, `contact_email`, `access_comments`, `relatedurl`, `general_comments`)
    VALUES(2491, "City of Santa Monica - Airport", "3223 Donald Douglas Loop", null, "Santa Monica", "CA", "90405", 2, 34.017563, -118.447475, "310-458-8516", null, null, "24 hours daily", "", null);
INSERT INTO `db`.`address`(`id`, `title`, `address_line1`, `address_line2`,`town`, `state_or_province`, `post_code`, `country_id`, `latitude`, `longtitude`, `contact_telephone1`,`contact_telephone2`, `contact_email`, `access_comments`, `relatedurl`, `general_comments`)
    VALUES(2492, "City of Santa Monica - Pier", "200 Santa Monica Pier", null, "Santa Monica", "CA", "90405", 2, 34.010021, -118.49583, "310-458-8516", null, null, "24 hours daily; pay lot", "", null);
INSERT INTO `db`.`address`(`id`, `title`, `address_line1`, `address_line2`,`town`, `state_or_province`, `post_code`, `country_id`, `latitude`, `longtitude`, `contact_telephone1`,`contact_telephone2`, `contact_email`, `access_comments`, `relatedurl`, `general_comments`)
    VALUES(2497, "Universal City Hilton", "333 Universal Terrace Pkwy", null, "Universal City", "CA", "91608", 2, 34.138717, -118.35904, "818-506-2500", null, null, "24 hours daily; pay lot; see valet for access", "", null);
INSERT INTO `db`.`address`(`id`, `title`, `address_line1`, `address_line2`,`town`, `state_or_province`, `post_code`, `country_id`, `latitude`, `longtitude`, `contact_telephone1`,`contact_telephone2`, `contact_email`, `access_comments`, `relatedurl`, `general_comments`)
    VALUES(2500, "Van Nuys Amtrak/Metrolink Station", "7724 Van Nuys Blvd", null, "Van Nuys", "CA", "91405", 2, 34.21108, -118.448704, "800-371-5465", null, null, "24 hours daily", "http://evconnect.com/", null);
INSERT INTO `db`.`address`(`id`, `title`, `address_line1`, `address_line2`,`town`, `state_or_province`, `post_code`, `country_id`, `latitude`, `longtitude`, `contact_telephone1`,`contact_telephone2`, `contact_email`, `access_comments`, `relatedurl`, `general_comments`)
    VALUES(2502, "Office Max - Home Depot", "7075 Firestone Blvd", null, "Downey", "CA", "90241", 2, 33.94756, -118.153806, "562-806-6600", null, null, "24 hours daily", "", null);
INSERT INTO `db`.`address`(`id`, `title`, `address_line1`, `address_line2`,`town`, `state_or_province`, `post_code`, `country_id`, `latitude`, `longtitude`, `contact_telephone1`,`contact_telephone2`, `contact_email`, `access_comments`, `relatedurl`, `general_comments`)
    VALUES(2504, "Scripps Memorial Hospital", "354 Santa Fe Dr", null, "Encinitas", "CA", "92024", 2, 33.037626, -117.283555, "", null, null, "24 hours daily", null, null);
INSERT INTO `db`.`address`(`id`, `title`, `address_line1`, `address_line2`,`town`, `state_or_province`, `post_code`, `country_id`, `latitude`, `longtitude`, `contact_telephone1`,`contact_telephone2`, `contact_email`, `access_comments`, `relatedurl`, `general_comments`)
    VALUES(2510, "City of Lancaster - City Hall", "44933 Fern Ave", null, "Lancaster", "CA", "93534", 2, 34.698914, -118.145218, "661-723-6000", null, null, "24 hours daily", "", null);
INSERT INTO `db`.`address`(`id`, `title`, `address_line1`, `address_line2`,`town`, `state_or_province`, `post_code`, `country_id`, `latitude`, `longtitude`, `contact_telephone1`,`contact_telephone2`, `contact_email`, `access_comments`, `relatedurl`, `general_comments`)
    VALUES(2512, "Hyatt at Fisherman's Wharf", "555 N Point St", null, "San Francisco", "CA", "94133", 2, 37.80619, -122.4152, "415-563-1234", null, null, "24 hours daily; pay lot; see valet for access", "", null);
INSERT INTO `db`.`address`(`id`, `title`, `address_line1`, `address_line2`,`town`, `state_or_province`, `post_code`, `country_id`, `latitude`, `longtitude`, `contact_telephone1`,`contact_telephone2`, `contact_email`, `access_comments`, `relatedurl`, `general_comments`)
    VALUES(2513, "Arden Fair Mall", "1689 Arden Way", null, "Sacramento", "CA", "95815", 2, 38.599693, -121.427045, "916-920-1167", null, null, "24 hours daily", "", null);
INSERT INTO `db`.`address`(`id`, `title`, `address_line1`, `address_line2`,`town`, `state_or_province`, `post_code`, `country_id`, `latitude`, `longtitude`, `contact_telephone1`,`contact_telephone2`, `contact_email`, `access_comments`, `relatedurl`, `general_comments`)
    VALUES(2525, "Palace Hotel", "2 New Montgomery St", null, "San Francisco", "CA", "94105", 2, 37.78881, -122.401, "415-512-1111", null, null, "24 hours daily", "", null);
INSERT INTO `db`.`address`(`id`, `title`, `address_line1`, `address_line2`,`town`, `state_or_province`, `post_code`, `country_id`, `latitude`, `longtitude`, `contact_telephone1`,`contact_telephone2`, `contact_email`, `access_comments`, `relatedurl`, `general_comments`)
    VALUES(2526, "Mark Hopkins InterContinental Hotel", "999 California St", null, "San Francisco", "CA", "94108", 2, 37.791405, -122.410248, "415-392-3434  877-798-3752", null, null, "24 hours daily; available for guest use only; see valet for access", "http://www.teslamotors.com/supercharger", null);
INSERT INTO `db`.`address`(`id`, `title`, `address_line1`, `address_line2`,`town`, `state_or_province`, `post_code`, `country_id`, `latitude`, `longtitude`, `contact_telephone1`,`contact_telephone2`, `contact_email`, `access_comments`, `relatedurl`, `general_comments`)
    VALUES(2531, "Hotel Sofitel", "8555 Beverly Blvd", null, "Los Angeles", "CA", "90048", 2, 34.07631, -118.377, "310-278-5444", null, null, "24 hours daily; for guest use only; see valet for access", "", null);
INSERT INTO `db`.`address`(`id`, `title`, `address_line1`, `address_line2`,`town`, `state_or_province`, `post_code`, `country_id`, `latitude`, `longtitude`, `contact_telephone1`,`contact_telephone2`, `contact_email`, `access_comments`, `relatedurl`, `general_comments`)
    VALUES(2538, "Balboa Golf Course", "16821 Burbank Blvd", null, "Encino", "CA", "91436", 2, 34.169242, -118.497212, "818-995-1170", null, null, "24 hours daily", "", null);
INSERT INTO `db`.`address`(`id`, `title`, `address_line1`, `address_line2`,`town`, `state_or_province`, `post_code`, `country_id`, `latitude`, `longtitude`, `contact_telephone1`,`contact_telephone2`, `contact_email`, `access_comments`, `relatedurl`, `general_comments`)
    VALUES(2540, "Tops Auto Park Garage", "6464 Sunset Blvd", null, "Hollywood", "CA", "90028", 2, 34.097928, -118.331, "", null, null, "For tenant and guest use only", "", null);
INSERT INTO `db`.`address`(`id`, `title`, `address_line1`, `address_line2`,`town`, `state_or_province`, `post_code`, `country_id`, `latitude`, `longtitude`, `contact_telephone1`,`contact_telephone2`, `contact_email`, `access_comments`, `relatedurl`, `general_comments`)
    VALUES(2544, "California State University - Northridge", "18111 Nordhoff St", null, "Northridge", "CA", "91330", 2, 34.241687, -118.528543, "818-677-1200", null, null, "24 hours daily; parking permit required", "", null);
INSERT INTO `db`.`address`(`id`, `title`, `address_line1`, `address_line2`,`town`, `state_or_province`, `post_code`, `country_id`, `latitude`, `longtitude`, `contact_telephone1`,`contact_telephone2`, `contact_email`, `access_comments`, `relatedurl`, `general_comments`)
    VALUES(2545, "California State University - Northridge", "18111 Nordhoff St", null, "Northridge", "CA", "91330", 2, 34.236853, -118.532588, "818-677-1200", null, null, "24 hours daily; parking permit required", "", null);
INSERT INTO `db`.`address`(`id`, `title`, `address_line1`, `address_line2`,`town`, `state_or_province`, `post_code`, `country_id`, `latitude`, `longtitude`, `contact_telephone1`,`contact_telephone2`, `contact_email`, `access_comments`, `relatedurl`, `general_comments`)
    VALUES(2555, "Getty Center", "1200 Getty Center Dr", null, "Los Angeles", "CA", "90049", 2, 34.077588, -118.474585, "310-440-7300", null, null, "Garage business hours; pay lot", "", null);
INSERT INTO `db`.`address`(`id`, `title`, `address_line1`, `address_line2`,`town`, `state_or_province`, `post_code`, `country_id`, `latitude`, `longtitude`, `contact_telephone1`,`contact_telephone2`, `contact_email`, `access_comments`, `relatedurl`, `general_comments`)
    VALUES(2563, "Los Angeles County - Arboretum", "301 N Baldwin Ave", null, "Arcadia", "CA", "91007", 2, 34.142727, -118.051275, "323-267-2023", null, null, "24 hours daily", "", null);
INSERT INTO `db`.`address`(`id`, `title`, `address_line1`, `address_line2`,`town`, `state_or_province`, `post_code`, `country_id`, `latitude`, `longtitude`, `contact_telephone1`,`contact_telephone2`, `contact_email`, `access_comments`, `relatedurl`, `general_comments`)
    VALUES(2567, "City of Glendora - City Hall", "114 S Vista Bonita Ave", null, "Glendora", "CA", "91741", 2, 34.13556, -117.864, "626-914-8200", null, null, "24 hours daily", "", null);
INSERT INTO `db`.`address`(`id`, `title`, `address_line1`, `address_line2`,`town`, `state_or_province`, `post_code`, `country_id`, `latitude`, `longtitude`, `contact_telephone1`,`contact_telephone2`, `contact_email`, `access_comments`, `relatedurl`, `general_comments`)
    VALUES(2573, "DoubleTree Hotel - Los Angeles - Westside", "6161 Centinela Ave", null, "Culver City", "CA", "90230", 2, 33.9826, -118.3966, "310-649-1776", null, null, "24 hours daily; guest use only", "", null);
INSERT INTO `db`.`address`(`id`, `title`, `address_line1`, `address_line2`,`town`, `state_or_province`, `post_code`, `country_id`, `latitude`, `longtitude`, `contact_telephone1`,`contact_telephone2`, `contact_email`, `access_comments`, `relatedurl`, `general_comments`)
    VALUES(2574, "Helms Bakery Building", "8800 Venice Blvd", null, "Los Angeles", "CA", "90034", 2, 34.029971, -118.385231, "310-204-1865", null, null, "24 hours daily", "", null);
INSERT INTO `db`.`address`(`id`, `title`, `address_line1`, `address_line2`,`town`, `state_or_province`, `post_code`, `country_id`, `latitude`, `longtitude`, `contact_telephone1`,`contact_telephone2`, `contact_email`, `access_comments`, `relatedurl`, `general_comments`)
    VALUES(2577, "Westfield MainPlace Mall", "2800 N Main St", null, "Santa Ana", "CA", "92705", 2, 33.777054, -117.870566, "714-547-7800", null, null, "6am-12am daily", "", null);
INSERT INTO `db`.`address`(`id`, `title`, `address_line1`, `address_line2`,`town`, `state_or_province`, `post_code`, `country_id`, `latitude`, `longtitude`, `contact_telephone1`,`contact_telephone2`, `contact_email`, `access_comments`, `relatedurl`, `general_comments`)
    VALUES(2589, "CITY OF SB EV2", "1115 Anacapa St", null, "Santa Barbara", "CA", "93101", 2, 34.423495, -119.70228, "888-758-4389", null, null, "24 hours daily", "http://www.chargepoint.com/", null);
INSERT INTO `db`.`address`(`id`, `title`, `address_line1`, `address_line2`,`town`, `state_or_province`, `post_code`, `country_id`, `latitude`, `longtitude`, `contact_telephone1`,`contact_telephone2`, `contact_email`, `access_comments`, `relatedurl`, `general_comments`)
    VALUES(2590, "California State University - Channel Islands", "1 University Dr", null, "Camarillo", "CA", "93012", 2, 34.165493, -119.04505, "805-437-8400", null, null, "24 hours daily", "", null);
INSERT INTO `db`.`address`(`id`, `title`, `address_line1`, `address_line2`,`town`, `state_or_province`, `post_code`, `country_id`, `latitude`, `longtitude`, `contact_telephone1`,`contact_telephone2`, `contact_email`, `access_comments`, `relatedurl`, `general_comments`)
    VALUES(2592, "Brea Downtown Parking", "101 S Brea Blvd", null, "Brea", "CA", "92821", 2, 33.919899, -117.898618, "714-990-7650", null, null, "Garage business hours; 4 hour parking limit", "", null);
INSERT INTO `db`.`address`(`id`, `title`, `address_line1`, `address_line2`,`town`, `state_or_province`, `post_code`, `country_id`, `latitude`, `longtitude`, `contact_telephone1`,`contact_telephone2`, `contact_email`, `access_comments`, `relatedurl`, `general_comments`)
    VALUES(2595, "Home Depot", "2745 Teller Rd", null, "Newbury Park", "CA", "91320", 2, 34.18997, -118.934393, "805-375-6680", null, null, "24 hours daily", "", null);
INSERT INTO `db`.`address`(`id`, `title`, `address_line1`, `address_line2`,`town`, `state_or_province`, `post_code`, `country_id`, `latitude`, `longtitude`, `contact_telephone1`,`contact_telephone2`, `contact_email`, `access_comments`, `relatedurl`, `general_comments`)
    VALUES(2596, "Lake Casitas Municipal Water District - Recreational Area", "Casitas Pass Rd & Baldwin Rd", null, "Oak View", "CA", "93022", 2, 34.418322, -119.3368, "805-649-2233", null, null, "8am-5pm daily", "", null);
INSERT INTO `db`.`address`(`id`, `title`, `address_line1`, `address_line2`,`town`, `state_or_province`, `post_code`, `country_id`, `latitude`, `longtitude`, `contact_telephone1`,`contact_telephone2`, `contact_email`, `access_comments`, `relatedurl`, `general_comments`)
    VALUES(2599, "San Dimas Park & Ride", "205 S San Dimas Ave", null, "San Dimas", "CA", "91773", 2, 34.105203, -117.807471, "909-394-6200", null, null, "24 hours daily", "", null);