INSERT INTO `db`.`connection_type`( `id`, `title`, `formal_name`) VALUES(7,"Avcon Connector","Avcon SAE J1772-2001");
INSERT INTO `db`.`connection_type`( `id`, `title`, `formal_name`) VALUES(4,"Blue Commando (2P+E)",null);
INSERT INTO `db`.`connection_type`( `id`, `title`, `formal_name`) VALUES(3,"BS1363 3 Pin 13 Amp","BS1363 / Type G");
INSERT INTO `db`.`connection_type`( `id`, `title`, `formal_name`) VALUES(32,"CCS (Type 1)","IEC 62196-3 Configuration EE");
INSERT INTO `db`.`connection_type`( `id`, `title`, `formal_name`) VALUES(33,"CCS (Type 2)","IEC 62196-3 Configuration FF");
INSERT INTO `db`.`connection_type`( `id`, `title`, `formal_name`) VALUES(16,"CEE 3 Pin",null);
INSERT INTO `db`.`connection_type`( `id`, `title`, `formal_name`) VALUES(17,"CEE 5 Pin",null);
INSERT INTO `db`.`connection_type`( `id`, `title`, `formal_name`) VALUES(23,"CEE 7/5",null);
INSERT INTO `db`.`connection_type`( `id`, `title`, `formal_name`) VALUES(28,"CEE 7/4 - Schuko - Type F","CEE 7/4");
INSERT INTO `db`.`connection_type`( `id`, `title`, `formal_name`) VALUES(18,"CEE+ 7 Pin",null);
INSERT INTO `db`.`connection_type`( `id`, `title`, `formal_name`) VALUES(2,"CHAdeMO","IEC 62196-3 Configuration AA");
INSERT INTO `db`.`connection_type`( `id`, `title`, `formal_name`) VALUES(13,"Europlug 2-Pin (CEE 7/16)","Europlug 2-Pin (CEE 7/16)");
INSERT INTO `db`.`connection_type`( `id`, `title`, `formal_name`) VALUES(1038,"GB-T AC - GB/T 20234.2 (Socket)","GB-T AC - GB/T 20234.2 (Socket)");
INSERT INTO `db`.`connection_type`( `id`, `title`, `formal_name`) VALUES(1039,"GB-T AC - GB/T 20234.2 (Tethered Cable)","GB-T AC - GB/T 20234.2 (Tethered Cable)");
INSERT INTO `db`.`connection_type`( `id`, `title`, `formal_name`) VALUES(1040,"GB-T DC - GB/T 20234.3","GB-T DC - GB/T 20234.3");
INSERT INTO `db`.`connection_type`( `id`, `title`, `formal_name`) VALUES(34,"IEC 60309 3-pin","IEC 60309 3-pin");
INSERT INTO `db`.`connection_type`( `id`, `title`, `formal_name`) VALUES(35,"IEC 60309 5-pin","IEC 60309 5-pin");
INSERT INTO `db`.`connection_type`( `id`, `title`, `formal_name`) VALUES(5,"LP Inductive","Large Paddle Inductive");
INSERT INTO `db`.`connection_type`( `id`, `title`, `formal_name`) VALUES(10,"NEMA 14-30",null);
INSERT INTO `db`.`connection_type`( `id`, `title`, `formal_name`) VALUES(11,"NEMA 14-50",null);
INSERT INTO `db`.`connection_type`( `id`, `title`, `formal_name`) VALUES(22,"NEMA 5-15R","NEMA 5-15R");
INSERT INTO `db`.`connection_type`( `id`, `title`, `formal_name`) VALUES(9,"NEMA 5-20R",null);
INSERT INTO `db`.`connection_type`( `id`, `title`, `formal_name`) VALUES(15,"NEMA 6-15",null);
INSERT INTO `db`.`connection_type`( `id`, `title`, `formal_name`) VALUES(14,"NEMA 6-20",null);
INSERT INTO `db`.`connection_type`( `id`, `title`, `formal_name`) VALUES(1042,"NEMA TT-30R",null);
INSERT INTO `db`.`connection_type`( `id`, `title`, `formal_name`) VALUES(36,"SCAME Type 3A (Low Power)",null);
INSERT INTO `db`.`connection_type`( `id`, `title`, `formal_name`) VALUES(26,"SCAME Type 3C (Schneider-Legrand)","IEC 62196-2 Type 3");
INSERT INTO `db`.`connection_type`( `id`, `title`, `formal_name`) VALUES(6,"SP Inductive","Small Paddle Inductive");
INSERT INTO `db`.`connection_type`( `id`, `title`, `formal_name`) VALUES(1037,"T13 - SEC1011 ( Swiss domestic 3-pin ) - Type J","T13/ IEC Type J");
INSERT INTO `db`.`connection_type`( `id`, `title`, `formal_name`) VALUES(30,"Tesla (Model S/X)",null);
INSERT INTO `db`.`connection_type`( `id`, `title`, `formal_name`) VALUES(8,"Tesla (Roadster)","Tesla Connector");
INSERT INTO `db`.`connection_type`( `id`, `title`, `formal_name`) VALUES(31,"Tesla Battery Swap","Tesla Battery Swap Station");
INSERT INTO `db`.`connection_type`( `id`, `title`, `formal_name`) VALUES(27,"Tesla Supercharger","Tesla Supercharger");
INSERT INTO `db`.`connection_type`( `id`, `title`, `formal_name`) VALUES(1041,"Three Phase 5-Pin (AS/NZ 3123)","AS/NZS 3123 Three Phase");
INSERT INTO `db`.`connection_type`( `id`, `title`, `formal_name`) VALUES(1,"Type 1 (J1772)","SAE J1772-2009");
INSERT INTO `db`.`connection_type`( `id`, `title`, `formal_name`) VALUES(25,"Type 2 (Socket Only)","IEC 62196-2 Type 2");
INSERT INTO `db`.`connection_type`( `id`, `title`, `formal_name`) VALUES(1036,"Type 2 (Tethered Connector) ","IEC 62196-2");
INSERT INTO `db`.`connection_type`( `id`, `title`, `formal_name`) VALUES(29,"Type I (AS 3112)","Type I/AS 3112/CPCS-CCC");
INSERT INTO `db`.`connection_type`( `id`, `title`, `formal_name`) VALUES(0,"Unknown","Not Specified");
INSERT INTO `db`.`connection_type`( `id`, `title`, `formal_name`) VALUES(24,"Wireless Charging",null);
INSERT INTO `db`.`connection_type`( `id`, `title`, `formal_name`) VALUES(21,"XLR Plug (4 pin)",null);