UPDATE `db`.`connection_type` SET `category`="type1"   WHERE `connection_type`.`id`=1;
UPDATE `db`.`connection_type` SET `category`="chademo" WHERE `connection_type`.`id`=2;
UPDATE `db`.`connection_type` SET `category`= "type1"   WHERE `connection_type`.`id`=3;
UPDATE `db`.`connection_type` SET `category`="type1"   WHERE `connection_type`.`id`=4;
UPDATE `db`.`connection_type` SET `category`= "type1"   WHERE `connection_type`.`id`=7;
UPDATE `db`.`connection_type` SET `category`= "type1"   WHERE `connection_type`.`id`=8;
UPDATE `db`.`connection_type` SET `category`= "type1"   WHERE `connection_type`.`id`=9;
UPDATE `db`.`connection_type` SET `category`= "type1"   WHERE `connection_type`.`id`=10;
UPDATE `db`.`connection_type` SET `category`= "type1"   WHERE `connection_type`.`id`=11;
UPDATE `db`.`connection_type` SET `category`= "type1"   WHERE `connection_type`.`id`=12;
UPDATE `db`.`connection_type` SET `category`= "type1"   WHERE `connection_type`.`id`=13;
UPDATE `db`.`connection_type` SET `category`= "type1"   WHERE `connection_type`.`id`=14;
UPDATE `db`.`connection_type` SET `category`= "type1"   WHERE `connection_type`.`id`=15;
UPDATE `db`.`connection_type` SET `category`= "type1"   WHERE `connection_type`.`id`=16;
UPDATE `db`.`connection_type` SET `category`= "type2"   WHERE `connection_type`.`id`=17;
UPDATE `db`.`connection_type` SET `category`= "type1"   WHERE `connection_type`.`id`=22;
UPDATE `db`.`connection_type` SET `category`= "type1"   WHERE `connection_type`.`id`=23;
UPDATE `db`.`connection_type` SET `category`= "type2"   WHERE `connection_type`.`id`=25;
UPDATE `db`.`connection_type` SET `category`= "type1"   WHERE `connection_type`.`id`=26;
UPDATE `db`.`connection_type` SET `category`= "teslasuc" WHERE `connection_type`.`id`=27;
UPDATE `db`.`connection_type` SET `category`= "type1"   WHERE `connection_type`.`id`=28;
UPDATE `db`.`connection_type` SET `category`= "type2"   WHERE `connection_type`.`id`=30;
UPDATE `db`.`connection_type` SET `category`= "ccs" WHERE `connection_type`.`id`=32;
UPDATE `db`.`connection_type` SET `category`= "ccs" WHERE `connection_type`.`id`=33;
UPDATE `db`.`connection_type` SET `category`= "type1"   WHERE `connection_type`.`id`=34;
UPDATE `db`.`connection_type` SET `category`= "type1"   WHERE `connection_type`.`id`=36;
UPDATE `db`.`connection_type` SET `category`= "type2"   WHERE `connection_type`.`id`=1036;
UPDATE `db`.`connection_type` SET `category`= "type1"   WHERE `connection_type`.`id`=1037;
UPDATE `db`.`connection_type` SET `category`= "type1"   WHERE `connection_type`.`id`=1043;