INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("United Kingdom", "GB", "EU");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("United States", "US", "NA");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Ireland", "IE", "EU");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Hong Kong", "HK", "AS");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Afghanistan", "AF", "AS");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Aland Islands", "AX", "EU");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Albania", "AL", "EU");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Algeria", "DZ", "AF");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("American Samoa", "AS", "OC");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Andorra", "AD", "EU");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Angola", "AO", "AF");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Anguilla", "AI", "NA");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Antarctica", "AQ", "AN");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Antigua And Barbuda", "AG", "NA");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Argentina", "AR", "SA");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Armenia", "AM", "AS");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Aruba", "AW", "NA");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Australia", "AU", "OC");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Austria", "AT", "EU");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Azerbaijan", "AZ", "AS");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Bahamas", "BS", "NA");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Bahrain", "BH", "AS");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Bangladesh", "BD", "AS");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Barbados", "BB", "NA");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Belarus", "BY", "EU");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Belgium", "BE", "EU");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Belize", "BZ", "NA");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Benin", "BJ", "AF");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Bermuda", "BM", "NA");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Bhutan", "BT", "AS");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Bolivia, Plurinational State Of", "BO", "SA");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Bonaire, Saint Eustatius And Saba", "BQ", null);
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Bosnia And Herzegovina", "BA", "EU");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Botswana", "BW", "AF");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Bouvet Island", "BV", "AN");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Brazil", "BR", "SA");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("British Indian Ocean Territory", "IO", "AS");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Brunei Darussalam", "BN", "AS");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Bulgaria", "BG", "EU");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Burkina Faso", "BF", "AF");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Burundi", "BI", "AF");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Cambodia", "KH", "AS");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Cameroon", "CM", "AF");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Canada", "CA", "NA");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Cape Verde", "CV", "AF");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Cayman Islands", "KY", "NA");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Central African Republic", "CF", "AF");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Chad", "TD", "AF");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Chile", "CL", "SA");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("China", "CN", "AS");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Christmas Island", "CX", "AS");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Cocos (Keeling); Islands", "CC", "AS");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Colombia", "CO", "SA");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Comoros", "KM", "AF");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Congo", "CG", "AF");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Congo, Democratic Republic Of The", "CD", "AF");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Cook Islands", "CK", "OC");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Costa Rica", "CR", "NA");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Cote D'Ivoire", "CI", "AF");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Croatia", "HR", "EU");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Cuba", "CU", "NA");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Curacao", "CW", null);
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Cyprus", "CY", "AS");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Czech Republic", "CZ", "EU");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Denmark", "DK", "EU");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Djibouti", "DJ", "AF");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Dominica", "DM", "NA");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Dominican Republic", "DO", "NA");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Ecuador", "EC", "SA");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Egypt", "EG", "AF");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("El Salvador", "SV", "NA");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Equatorial Guinea", "GQ", "AF");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Eritrea", "ER", "AF");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Estonia", "EE", "EU");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Ethiopia", "ET", "AF");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Falkland Islands (Malvinas);", "FK", "SA");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Faroe Islands", "FO", "EU");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Fiji", "FJ", "OC");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Finland", "FI", "EU");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("France", "FR", "EU");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("French Guiana", "GF", "SA");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("French Polynesia", "PF", "OC");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("French Southern Territories", "TF", "AN");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Gabon", "GA", "AF");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Gambia", "GM", "AF");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Georgia", "GE", "AS");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Germany", "DE", "EU");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Ghana", "GH", "AF");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Gibraltar", "GI", "EU");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Greece", "GR", "EU");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Greenland", "GL", "NA");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Grenada", "GD", "NA");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Guadeloupe", "GP", "NA");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Guam", "GU", "OC");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Guatemala", "GT", "NA");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Guernsey", "GG", "EU");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Guinea", "GN", "AF");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Guinea-Bissau", "GW", "AF");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Guyana", "GY", "SA");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Haiti", "HT", "NA");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Heard Island And Mcdonald Islands", "HM", "AN");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Holy See (Vatican City State);", "VA", "EU");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Honduras", "HN", "NA");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Hungary", "HU", "EU");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Iceland", "IS", "EU");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("India", "IN", "AS");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Indonesia", null, "AS");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Iran, Islamic Republic Of", "IR", "AS");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Iraq", "IQ", "AS");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Isle Of Man", "IM", "EU");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Israel", "IL", "AS");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Italy", "IT", "EU");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Jamaica", "JM", "NA");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Japan", "JP", "AS");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Jersey", "JE", "EU");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Jordan", "JO", "AS");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Kazakhstan", "KZ", "AS");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Kenya", "KE", "AF");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Kiribati", "KI", "OC");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Korea, Democratic People's Rep.", "KP", "AS");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Korea, Republic Of", "KR", "AS");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Kuwait", "KW", "AS");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Kyrgyzstan", "KG", "AS");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Lao People's Democratic Republic", "LA", "AS");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Latvia", "LV", "EU");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Lebanon", "LB", "AS");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Lesotho", "LS", "AF");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Liberia", "LR", "AF");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Libyan Arab Jamahiriya", "LY", "AF");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Liechtenstein", "LI", "EU");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Lithuania", "LT", "EU");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Luxembourg", "LU", "EU");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Macao", "MO", "AS");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Macedonia", "MK", "EU");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Madagascar", "MG", "AF");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Malawi", "MW", "AF");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Malaysia", "MY", "AS");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Maldives", "MV", "AS");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Mali", "ML", "AF");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Malta", "MT", "EU");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Marshall Islands", "MH", "OC");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Martinique", "MQ", "NA");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Mauritania", "MR", "AF");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Mauritius", "MU", "AF");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Mayotte", "YT", "AF");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Mexico", "MX", "NA");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Micronesia, Federated States Of", "FM", "OC");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Moldova, Republic Of", "MD", "EU");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Monaco", "MC", "EU");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Mongolia", "MN", "AS");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Montenegro", "ME", "EU");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Montserrat", "MS", "NA");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Morocco", "MA", "AF");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Mozambique", "MZ", "AF");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Myanmar", "MM", "AS");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Namibia", "NA", "AF");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Nauru", "NR", "OC");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Nepal", "NP", "AS");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Netherlands", "NL", "EU");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("New Caledonia", "NC", "OC");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("New Zealand", "NZ", "OC");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Nicaragua", "NI", "NA");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Niger", "NE", "AF");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Nigeria", "NG", "AF");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Niue", "NU", "OC");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Norfolk Island", "NF", "OC");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Northern Mariana Islands", "MP", "OC");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Norway", "NO", "EU");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Oman", "OM", "AS");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Pakistan", "PK", "AS");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Palau", "PW", "OC");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Palestinian Territory, Occupied", "PS", "AS");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Panama", "PA", "NA");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Papua New Guinea", "PG", "OC");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Paraguay", "PY", "SA");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Peru", "PE", "SA");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Philippines", "PH", "AS");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Pitcairn", "PN", "OC");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Poland", "PL", "EU");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Portugal", "PT", "EU");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Puerto Rico", "PR", "NA");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Qatar", "QA", "AS");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Reunion", "RE", "AF");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Romania", "RO", "EU");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Russian Federation", "RU", "EU");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Rwanda", "RW", "AF");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Saint Barthelemy", "BL", "NA");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Saint Helena", "SH", "AF");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Saint Kitts And Nevis", "KN", "NA");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Saint Lucia", "LC", "NA");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Saint Martin (French Part);", "MF", "NA");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Saint Pierre And Miquelon", "PM", "NA");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Saint Vincent And The Grenadines", "VC", "NA");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Samoa", "WS", "OC");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("San Marino", "SM", "EU");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Sao Tome And Principe", "ST", "AF");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Saudi Arabia", "SA", "AS");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Senegal", "SN", "AF");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Serbia", "RS", "EU");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Seychelles", "SC", "AF");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Sierra Leone", "SL", "AF");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Singapore", "SG", "AS");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Sint Maarten (Dutch Part);", "SX", null);
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Slovakia", "SK", "EU");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Slovenia", "SI", "EU");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Solomon Islands", "SB", "OC");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Somalia", "SO", "AF");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("South Africa", "ZA", "AF");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("South Georgia", "GS", "AN");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Spain", "ES", "EU");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Sri Lanka", "LK", "AS");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Sudan", "SD", "AF");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Suriname", "SR", "SA");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Svalbard And Jan Mayen", "SJ", "EU");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Swaziland", "SZ", "AF");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Sweden", "SE", "EU");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Switzerland", "CH", "EU");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Syrian Arab Republic", "SY", "AS");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Taiwan, Province Of China", "TW", "AS");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Tajikistan", "TJ", "AS");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Tanzania, United Republic Of", "TZ", "AF");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Thailand", "TH", "AS");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Timor-Leste", "TL", "AS");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Togo", "TG", "AF");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Tokelau", "TK", "OC");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Tonga", "TO", "OC");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Trinidad And Tobago", "TT", "NA");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Tunisia", "TN", "AF");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Turkey", "TR", "EU");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Turkmenistan", "TM", "AS");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Turks And Caicos Islands", "TC", "NA");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Tuvalu", "TV", "OC");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Uganda", "UG", "AF");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Ukraine", "UA", "EU");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("United Arab Emirates", "AE", "AS");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("United States Minor Outlying Islands", "UM", "OC");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Uruguay", "UY", "SA");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Uzbekistan", "UZ", "AS");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Vanuatu", "VU", "OC");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Venezuela, Bolivarian Republic Of", "VE", "SA");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Viet Nam", "VN", "AS");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Virgin Islands, British", "VG", "NA");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Virgin Islands, U.S.", "VI", "NA");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Wallis And Futuna", "WF", "OC");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Western Sahara", "EH", "AF");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Yemen", "YE", "AS");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Zambia", "ZM", "AF");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Zimbabwe", "ZW", "AF");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("South Sudan", "SS", "AF");
INSERT INTO `db`.`country` (`title`, `isocode`, `continent_code`) VALUES ("Kosovo", "XK", "EU");