INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("KESH (Albanian Power Corporation)", 7);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("OSHEE (Electric Power Distribution Operator)", 7);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("SDC (Groupe SONELGAZ)[1]", 8);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("Ausgrid (previously EnergyAustralia)", 18);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("AusNet Services (previously SP AusNet)", 18);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("Ashuganj Power Station Company Limited", 23);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("Bangladesh Power Development Board", 23);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("Dhaka Electric Supply Company Limited", 23);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("Barbados Light and Power Company", 24);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("Eandis [nl]", 26);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("Eandis:IMEA", 26);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("Gaselwest", 26);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("Infrax [fr]", 26);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("Infrax:P.B.E.", 26);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("Ores:Intermosane", 26);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("Enel São Paulo", 36);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("Energisa", 36);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("Light", 36);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("Alectra Utilities", 44);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("AltaLink", 44);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("ATCO Electric", 44);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("ATCO Power", 44);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("China Southern Power Grid", 50);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("State Grid Corporation of China", 50);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("ISA INTERCOLOMBIA (Grupo ISA)[2]", 53);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("Instituto Costarricense de Electricidad", 58);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("Compañía Nacional de Fuerza y Luz (CNFL)", 58);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("Coopeguanacaste", 58);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("HEP Operator distribucijskog sustava (HEP ODS)", 60);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("Electricity Authority of Cyprus", 63);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("CEZ Distribuce", 64);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("DONG Energy - now Orsted", 65);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("Energi & MiljøForum Thy/Mors", 65);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("Energi Fyn", 65);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("Canal Company for Electricity Distribution[1]", 70);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("Estonia Estonia[2]", 70);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("220 Energia", 70);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("Caruna", 79);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("Elenia", 79);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("Enedis", 80);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("Cie Nationale du Rhône SA - Électricité de France SA", 80);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("Electricité de Strasbourg (ES Energies)", 80);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("E.ON", 87);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("EnBW", 87);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("Entega", 87);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("EWR", 87);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("HEDNO", 90);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("Adani Electricity Mumbai Limited[4]", 106);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("Ajmer Vidyut Vitran Nigam Ltd[5]", 106);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("Andhra Pradesh State Electricity Board (APSEB), Andhra Pradesh", 106);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("Southern Power Distribution Company of Andhra Pradesh Limited", 106);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("Assam Power Distribution Company Limited (APDCL), Assam", 106);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("Perusahaan Listrik Negara", 107);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("A2A", 112);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("Edison S.p.A.", 112);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("Enel", 112);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("Tavanir", 108);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("Israel Electric Corporation", 111);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("Chubu Electric Power Company", 114);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("Chugoku Electric Power Company", 114);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("Hokkaido Electric Power Company", 114);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("Hokuriku Electric Power Company", 114);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("Kenya Power and Lighting Company", 118);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("Inter RAO", 125);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("Latvenergo", 125);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("Electricité Du Liban (EDL)", 126);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("AB ESO", 131);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("Macau Macau", 131);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("CEM", 131);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("Jirama", 135);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("Hydelec Madagascar", 135);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("Comisión Federal de Electricidad", 146);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("Central North Regional Electricity Distributor", 156);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("City of Windhoek", 156);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("Erongo Red", 156);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("NamPower", 156);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("Nored Electricity", 156);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("Nepal Electricity Authority", 158);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("Coteq Netbeheer", 159);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("Enduris", 159);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("Enexis", 159);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("Alpine Energy", 161);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("Aurora Energy", 161);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("Buller Electricity", 161);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("Centralines", 161);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("Counties Power", 161);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("Eastland Network", 161);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("Abuja Electricity Distribution Company", 164);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("Benin Electricity Distribution Company", 164);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("Eko Electricity Distribution Company", 164);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("Enugu Electricity Distribution Company", 164);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("EVN AD Skopje (subsidiary of EVN Group)", 134);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("Faisalabad Electric Supply Company", 170);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("Gujranwala Electric Power Company", 170);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("Hub Power Company", 170);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("Hyderabad Electric Supply Company", 170);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("See also: List of companies of the Philippines § Utilities", 177);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("National Power Corporation", 177);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("National Grid Corporation of the Philippines", 177);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("Transmission Corporation of the Philippines", 177);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("Enea Operator Sp. z o.o.", 179);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("Energa Operator SA", 179);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("PGE Dystrybucja SA", 179);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("Energias de Portugal", 180);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("Redes Energéticas Nacionais", 180);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("Kahramaa", 182);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("Electrica Distribuție Muntenia Nord SA", 184);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("Electrica Transilvania Nord SA", 184);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("Electrica Transilvania Sud SA", 184);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("Enel Distribuție Banat SA", 184);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("IDGC Holding", 185);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("IDGC of Center", 185);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("IDGC of the North-West", 185);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("IDGC of the Urals", 185);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("Elektroprivreda Srbije", 199);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("ENEKOD", 199);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("Restart Energy DOO", 199);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("Singapore Power", 202);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("Elektro Celje", 205);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("Elektro Gorenjska", 205);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("Elektro Ljubljana", 205);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("Eskom", 208);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("Korea Electric Power Corporation", 120);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("Korea Electric Power Corporation", 121);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("Red Eléctrica de España", 210);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("Ceylon Electricity Board", 211);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("Lanka Electricity Company", 211);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("Götene Elförening ek. för.", 216);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("Gislaved Energi AB", 216);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("Öresundskraft", 216);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("Sala-Heby Energi Elnät AB", 216);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("BKW", 217);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("Groupe E", 217);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("Taiwan Power Company", 219);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("TANESCO-TZ does not allow any other firm to provide electricity", 221);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("Electricity Generating Authority of Thailand", 222);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("Metropolitan Electricity Authority", 222);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("Provincial Electricity Authority", 222);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("Akdeniz Electricity Distribution Company", 229);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("Akedaş Electricity Distribution Corp.", 229);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("Aras Electricity Distribution Company", 229);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("Abu Dhabi - Abu Dhabi Distribution Company (ADDC)[18] and Al Ain Distribution Company (AADC)[19]", 235);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("Dubai - Dubai Electricity & Water Authority (DEWA)", 235);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("Sharjah - Sharjah Electricity & Water Authority (SEWA)", 235);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("Rest of UAE - Federal Electricity & Water Authority (FEWA)", 235);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("Electricity North West (previously NORWEB)", 1);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("ESB Networks (SWALEC)", 1);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("Alabama Power, a part of the Southern Company, PowerSouth Energy Cooperative, Inc., Wiregrass Electric Cooperative, Tennessee Valley Authority", 2);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("Public Service Company, American Electric Power", 2);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("MidAmerican Energy", 2);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("Kansas City Power & Light, Westar Energy, Kansas City Board of Public Utilities", 2);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("SWEPCO (a subsidiary of American Electric Power), Entergy, CLECO", 2);
INSERT INTO `db`.`current_provider`(`name`, `country_id`) VALUES("UTE", 237);
